// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCigI9M95rFLq9pPVFHYRxP-XGIvjXTRWI',
    appId: '1:109713039512:web:0db2a15a56c2dfb981f0ed',
    messagingSenderId: '109713039512',
    projectId: 'flutterauthapp-66622',
    authDomain: 'flutterauthapp-66622.firebaseapp.com',
    storageBucket: 'flutterauthapp-66622.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA84_K0eX4bN-WuViQcL-ttXKNlvg-jy0s',
    appId: '1:109713039512:android:9657cec5dd4f456b81f0ed',
    messagingSenderId: '109713039512',
    projectId: 'flutterauthapp-66622',
    storageBucket: 'flutterauthapp-66622.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcqk7FihGiTIhfk4XTXQGr948q6wgiQIY',
    appId: '1:109713039512:ios:721766e5fb7bb22681f0ed',
    messagingSenderId: '109713039512',
    projectId: 'flutterauthapp-66622',
    storageBucket: 'flutterauthapp-66622.firebasestorage.app',
    iosBundleId: 'com.example.financeTrackerV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcqk7FihGiTIhfk4XTXQGr948q6wgiQIY',
    appId: '1:109713039512:ios:721766e5fb7bb22681f0ed',
    messagingSenderId: '109713039512',
    projectId: 'flutterauthapp-66622',
    storageBucket: 'flutterauthapp-66622.firebasestorage.app',
    iosBundleId: 'com.example.financeTrackerV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCigI9M95rFLq9pPVFHYRxP-XGIvjXTRWI',
    appId: '1:109713039512:web:cb1c76dfb699a1aa81f0ed',
    messagingSenderId: '109713039512',
    projectId: 'flutterauthapp-66622',
    authDomain: 'flutterauthapp-66622.firebaseapp.com',
    storageBucket: 'flutterauthapp-66622.firebasestorage.app',
  );
}
